import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { readForwardedEnquiry, readLeadConversationLinks } from './forwarded-enquiries.server.ts';
import { PGlite } from '@electric-sql/pglite';
const migration = new URL('../../../neon/migrations/20260929107000_whatsapp_forwarded_enquiries.sql', import.meta.url);
const id = (n) => `00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('manual forward keeps forwarder separate, creates one CRM query, and never opts in or opens a reply window', async () => {
 const db = new PGlite(); const q = async (s,p=[]) => (await db.query(s,p)).rows;
 try {
  await db.exec(`CREATE TABLE staff_users(id uuid PRIMARY KEY, active boolean, branch_id uuid,name_zh text,name_en text,email text);
    CREATE TABLE staff_roles(staff_user_id uuid,role text);
    CREATE TABLE crm_contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text,email text,phone text,opt_in_whatsapp boolean DEFAULT false,last_inbound_at timestamptz,updated_at timestamptz DEFAULT now());
    CREATE TABLE crm_leads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),contact_id uuid,assigned_agent_id uuid,stage text DEFAULT 'new',intent text DEFAULT 'buyer',source text,note text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
    CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid,action text,subject_type text,subject_id uuid,metadata jsonb,created_at timestamptz DEFAULT now());
    CREATE TABLE whatsapp_conversations(id uuid PRIMARY KEY,contact_id uuid,created_at timestamptz DEFAULT now());
    CREATE FUNCTION wa_can_read_conversation(uuid,uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT $1='${id(2)}'::uuid AND $2='${id(40)}'::uuid $$;
    CREATE TABLE crm_activities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lead_id uuid,contact_id uuid,staff_user_id uuid,activity_type text,body text,due_at timestamptz,completed_at timestamptz,created_at timestamptz DEFAULT now());`);
  await db.exec(readFileSync(migration,'utf8'));
  await q("INSERT INTO staff_users VALUES($1,true,$4,'經理',NULL,NULL),($2,true,$4,'轉交同事',NULL,NULL),($3,true,$5,'別區同事',NULL,NULL)",[id(1),id(2),id(3),id(4),id(5)]);
  await q("INSERT INTO staff_roles VALUES($1,'manager'),($2,'agent'),($3,'agent')",[id(1),id(2),id(3)]);
  const args=[id(2),id(20),'朋友轉來的客戶查詢',null,'未核實：61234567',null,null,'朋友轉交',null,null,null];
  const [first]=await q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',args);
  const [duplicate]=await q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',args);
  assert.equal(first.created,true); assert.equal(duplicate.created,false); assert.equal(first.lead_id,duplicate.lead_id);
  const [lead]=await q('SELECT source,contact_id,assigned_agent_id FROM crm_leads WHERE id=$1',[first.lead_id]);
  assert.equal(lead.source,'manual_forward'); assert.equal(lead.contact_id,null); assert.equal(lead.assigned_agent_id,id(2));
  assert.equal((await q('SELECT count(*)::int AS n FROM crm_contacts'))[0].n,0);
  assert.equal((await q('SELECT count(*)::int AS n FROM crm_leads'))[0].n,1);
  assert.equal((await q('SELECT count(*)::int AS n FROM crm_activities WHERE lead_id=$1',[first.lead_id]))[0].n,0);
  const visible=await readForwardedEnquiry(first.lead_id,{staffId:id(2)},q);
  assert.equal(visible.original_customer_contact,'未核實：61234567');
  assert.equal(await readForwardedEnquiry(first.lead_id,{staffId:id(3)},q),null);
  const followArgs=[id(1),id(23),'另一宗轉交',null,null,null,null,'同事轉交','致電核實',new Date('2026-10-01T02:00:00Z').toISOString(),id(2)];
  const [follow]=await q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',followArgs);
  assert.equal((await q('SELECT count(*)::int AS n FROM crm_activities WHERE lead_id=$1 AND staff_user_id=$2',[follow.lead_id,id(2)]))[0].n,1);
  await q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',followArgs);
  assert.equal((await q('SELECT count(*)::int AS n FROM crm_activities WHERE lead_id=$1',[follow.lead_id]))[0].n,1);
  await assert.rejects(q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',[...args.slice(0,2),'changed',...args.slice(3)]),/WA_FORWARD_REQUEST_CONFLICT/);
  await assert.rejects(q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',[id(3),id(21),...args.slice(2,10),id(2)]),/WA_FORWARD_OWNER_SCOPE/);
  await q('INSERT INTO crm_contacts(id) VALUES($1)',[id(30)]);
  await q("INSERT INTO crm_leads(id,contact_id,assigned_agent_id,source) VALUES($1,$2,$3,'whatsapp')",[id(31),id(30),id(2)]);
  await q('INSERT INTO whatsapp_conversations(id,contact_id) VALUES($1,$3),($2,$3)',[id(40),id(41),id(30)]);
  assert.deepEqual((await readLeadConversationLinks(id(31),{staffId:id(2)},q)).map((r)=>r.id),[id(40)]);
  assert.deepEqual(await readLeadConversationLinks(id(31),{staffId:id(3)},q),[]);
  const [edited]=await q('SELECT * FROM wa_update_lead_contact($1::uuid,$2::uuid,$3,$4)',[id(2),id(31),'原客戶姓名','customer@example.com']);
  assert.equal(edited.contact_id,id(30));
  assert.equal((await q('SELECT name,email,opt_in_whatsapp,last_inbound_at FROM crm_contacts WHERE id=$1',[id(30)]))[0].opt_in_whatsapp,false);
  assert.equal((await q("SELECT count(*)::int AS n FROM audit_logs WHERE action='lead.contact.update' AND subject_id=$1",[id(30)]))[0].n,1);
  await assert.rejects(q('SELECT * FROM wa_update_lead_contact($1::uuid,$2::uuid,$3,$4)',[id(3),id(31),'越權',null]),/WA_CONTACT_SCOPE/);
  await assert.rejects(q('SELECT * FROM wa_update_lead_contact($1::uuid,$2::uuid,$3,$4)',[id(2),first.lead_id,'無聯絡資料',null]),/WA_CONTACT_SCOPE/);
  await q('UPDATE staff_users SET active=false WHERE id=$1',[id(2)]);
  await assert.rejects(q('SELECT * FROM wa_capture_forwarded_enquiry($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10::timestamptz,$11::uuid)',[id(2),id(22),...args.slice(2)]),/WA_FORWARD_ACTOR_FORBIDDEN/);
 } finally { await db.close(); }
});
