/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CastlePeakRoadRouteImport } from './routes/castle-peak-road'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CastlePeakRoadIndexRouteImport } from './routes/castle-peak-road.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertyListingNoRouteImport } from './routes/property.$listingNo'
import { Route as EstateSlugRouteImport } from './routes/estate.$slug'
import { Route as DistrictTsuenWanRouteImport } from './routes/district.tsuen-wan'
import { Route as DistrictTingKauRouteImport } from './routes/district.ting-kau'
import { Route as DistrictShamTsengRouteImport } from './routes/district.sham-tseng'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard.inquiries'
import { Route as CastlePeakRoadSegmentRouteImport } from './routes/castle-peak-road.$segment'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as ApiMlsSyncRouteImport } from './routes/api.mls-sync'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminBlastsRouteImport } from './routes/admin.blasts'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'
import { Route as DashboardPropertyNewRouteImport } from './routes/dashboard.property.new'
import { Route as DashboardPropertyIdRouteImport } from './routes/dashboard.property.$id'
import { Route as ApiWoztellWebhookRouteImport } from './routes/api.woztell.webhook'
import { Route as ApiLiveAgentSessionRouteImport } from './routes/api.live-agent.session'
import { Route as ApiLiveAgentMessageRouteImport } from './routes/api.live-agent.message'
import { Route as ApiLiveAgentHandoffRouteImport } from './routes/api.live-agent.handoff'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings_.new'
import { Route as AdminListingsIdRouteImport } from './routes/admin.listings_.$id'
import { Route as ApiAdminWoztellSendRouteImport } from './routes/api.admin.woztell.send'
import { Route as ApiAdminMediaUploadRouteImport } from './routes/api.admin.media.upload'
import { Route as ApiAdminJobsSendQueueRouteImport } from './routes/api.admin.jobs.send-queue'
import { Route as ApiAdminAiRebuildKnowledgeRouteImport } from './routes/api.admin.ai.rebuild-knowledge'
import { Route as ApiAdminCampaignsIdQueueRouteImport } from './routes/api.admin.campaigns.$id.queue'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CastlePeakRoadRoute = CastlePeakRoadRouteImport.update({
  id: '/castle-peak-road',
  path: '/castle-peak-road',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CastlePeakRoadIndexRoute = CastlePeakRoadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CastlePeakRoadRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertyListingNoRoute = PropertyListingNoRouteImport.update({
  id: '/property/$listingNo',
  path: '/property/$listingNo',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateSlugRoute = EstateSlugRouteImport.update({
  id: '/estate/$slug',
  path: '/estate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictTsuenWanRoute = DistrictTsuenWanRouteImport.update({
  id: '/district/tsuen-wan',
  path: '/district/tsuen-wan',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictTingKauRoute = DistrictTingKauRouteImport.update({
  id: '/district/ting-kau',
  path: '/district/ting-kau',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictShamTsengRoute = DistrictShamTsengRouteImport.update({
  id: '/district/sham-tseng',
  path: '/district/sham-tseng',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const CastlePeakRoadSegmentRoute = CastlePeakRoadSegmentRouteImport.update({
  id: '/$segment',
  path: '/$segment',
  getParentRoute: () => CastlePeakRoadRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlsSyncRoute = ApiMlsSyncRouteImport.update({
  id: '/api/mls-sync',
  path: '/api/mls-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlastsRoute = AdminBlastsRouteImport.update({
  id: '/blasts',
  path: '/blasts',
  getParentRoute: () => AdminRoute,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertyNewRoute = DashboardPropertyNewRouteImport.update({
  id: '/property/new',
  path: '/property/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertyIdRoute = DashboardPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWoztellWebhookRoute = ApiWoztellWebhookRouteImport.update({
  id: '/api/woztell/webhook',
  path: '/api/woztell/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveAgentSessionRoute = ApiLiveAgentSessionRouteImport.update({
  id: '/api/live-agent/session',
  path: '/api/live-agent/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveAgentMessageRoute = ApiLiveAgentMessageRouteImport.update({
  id: '/api/live-agent/message',
  path: '/api/live-agent/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveAgentHandoffRoute = ApiLiveAgentHandoffRouteImport.update({
  id: '/api/live-agent/handoff',
  path: '/api/live-agent/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings_/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminWoztellSendRoute = ApiAdminWoztellSendRouteImport.update({
  id: '/api/admin/woztell/send',
  path: '/api/admin/woztell/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaUploadRoute = ApiAdminMediaUploadRouteImport.update({
  id: '/api/admin/media/upload',
  path: '/api/admin/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminJobsSendQueueRoute = ApiAdminJobsSendQueueRouteImport.update({
  id: '/api/admin/jobs/send-queue',
  path: '/api/admin/jobs/send-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiRebuildKnowledgeRoute =
  ApiAdminAiRebuildKnowledgeRouteImport.update({
    id: '/api/admin/ai/rebuild-knowledge',
    path: '/api/admin/ai/rebuild-knowledge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCampaignsIdQueueRoute =
  ApiAdminCampaignsIdQueueRouteImport.update({
    id: '/api/admin/campaigns/$id/queue',
    path: '/api/admin/campaigns/$id/queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/castle-peak-road': typeof CastlePeakRoadRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/blasts': typeof AdminBlastsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/mls-sync': typeof ApiMlsSyncRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/castle-peak-road/$segment': typeof CastlePeakRoadSegmentRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/ting-kau': typeof DistrictTingKauRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/admin/': typeof AdminIndexRoute
  '/castle-peak-road/': typeof CastlePeakRoadIndexRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/api/live-agent/handoff': typeof ApiLiveAgentHandoffRoute
  '/api/live-agent/message': typeof ApiLiveAgentMessageRoute
  '/api/live-agent/session': typeof ApiLiveAgentSessionRoute
  '/api/woztell/webhook': typeof ApiWoztellWebhookRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
  '/api/admin/ai/rebuild-knowledge': typeof ApiAdminAiRebuildKnowledgeRoute
  '/api/admin/jobs/send-queue': typeof ApiAdminJobsSendQueueRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/woztell/send': typeof ApiAdminWoztellSendRoute
  '/api/admin/campaigns/$id/queue': typeof ApiAdminCampaignsIdQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/blasts': typeof AdminBlastsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/mls-sync': typeof ApiMlsSyncRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/castle-peak-road/$segment': typeof CastlePeakRoadSegmentRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/ting-kau': typeof DistrictTingKauRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/admin': typeof AdminIndexRoute
  '/castle-peak-road': typeof CastlePeakRoadIndexRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/api/live-agent/handoff': typeof ApiLiveAgentHandoffRoute
  '/api/live-agent/message': typeof ApiLiveAgentMessageRoute
  '/api/live-agent/session': typeof ApiLiveAgentSessionRoute
  '/api/woztell/webhook': typeof ApiWoztellWebhookRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
  '/api/admin/ai/rebuild-knowledge': typeof ApiAdminAiRebuildKnowledgeRoute
  '/api/admin/jobs/send-queue': typeof ApiAdminJobsSendQueueRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/woztell/send': typeof ApiAdminWoztellSendRoute
  '/api/admin/campaigns/$id/queue': typeof ApiAdminCampaignsIdQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/castle-peak-road': typeof CastlePeakRoadRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/blasts': typeof AdminBlastsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/mls-sync': typeof ApiMlsSyncRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/castle-peak-road/$segment': typeof CastlePeakRoadSegmentRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/ting-kau': typeof DistrictTingKauRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/admin/': typeof AdminIndexRoute
  '/castle-peak-road/': typeof CastlePeakRoadIndexRoute
  '/admin/listings_/$id': typeof AdminListingsIdRoute
  '/admin/listings_/new': typeof AdminListingsNewRoute
  '/api/live-agent/handoff': typeof ApiLiveAgentHandoffRoute
  '/api/live-agent/message': typeof ApiLiveAgentMessageRoute
  '/api/live-agent/session': typeof ApiLiveAgentSessionRoute
  '/api/woztell/webhook': typeof ApiWoztellWebhookRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
  '/api/admin/ai/rebuild-knowledge': typeof ApiAdminAiRebuildKnowledgeRoute
  '/api/admin/jobs/send-queue': typeof ApiAdminJobsSendQueueRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/woztell/send': typeof ApiAdminWoztellSendRoute
  '/api/admin/campaigns/$id/queue': typeof ApiAdminCampaignsIdQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/castle-peak-road'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/sitemap.xml'
    | '/account/$pathname'
    | '/admin/blasts'
    | '/admin/cms'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/segments'
    | '/admin/whatsapp'
    | '/api/mls-sync'
    | '/auth/$pathname'
    | '/auth/login'
    | '/blog/$slug'
    | '/castle-peak-road/$segment'
    | '/dashboard/inquiries'
    | '/district/sham-tseng'
    | '/district/ting-kau'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/admin/'
    | '/castle-peak-road/'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/api/live-agent/handoff'
    | '/api/live-agent/message'
    | '/api/live-agent/session'
    | '/api/woztell/webhook'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
    | '/api/admin/ai/rebuild-knowledge'
    | '/api/admin/jobs/send-queue'
    | '/api/admin/media/upload'
    | '/api/admin/woztell/send'
    | '/api/admin/campaigns/$id/queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/sitemap.xml'
    | '/account/$pathname'
    | '/admin/blasts'
    | '/admin/cms'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/segments'
    | '/admin/whatsapp'
    | '/api/mls-sync'
    | '/auth/$pathname'
    | '/auth/login'
    | '/blog/$slug'
    | '/castle-peak-road/$segment'
    | '/dashboard/inquiries'
    | '/district/sham-tseng'
    | '/district/ting-kau'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/admin'
    | '/castle-peak-road'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/api/live-agent/handoff'
    | '/api/live-agent/message'
    | '/api/live-agent/session'
    | '/api/woztell/webhook'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
    | '/api/admin/ai/rebuild-knowledge'
    | '/api/admin/jobs/send-queue'
    | '/api/admin/media/upload'
    | '/api/admin/woztell/send'
    | '/api/admin/campaigns/$id/queue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/castle-peak-road'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/sitemap.xml'
    | '/account/$pathname'
    | '/admin/blasts'
    | '/admin/cms'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/segments'
    | '/admin/whatsapp'
    | '/api/mls-sync'
    | '/auth/$pathname'
    | '/auth/login'
    | '/blog/$slug'
    | '/castle-peak-road/$segment'
    | '/dashboard/inquiries'
    | '/district/sham-tseng'
    | '/district/ting-kau'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/admin/'
    | '/castle-peak-road/'
    | '/admin/listings_/$id'
    | '/admin/listings_/new'
    | '/api/live-agent/handoff'
    | '/api/live-agent/message'
    | '/api/live-agent/session'
    | '/api/woztell/webhook'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
    | '/api/admin/ai/rebuild-knowledge'
    | '/api/admin/jobs/send-queue'
    | '/api/admin/media/upload'
    | '/api/admin/woztell/send'
    | '/api/admin/campaigns/$id/queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CastlePeakRoadRoute: typeof CastlePeakRoadRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListingsRoute: typeof ListingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
  ApiMlsSyncRoute: typeof ApiMlsSyncRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DistrictShamTsengRoute: typeof DistrictShamTsengRoute
  DistrictTingKauRoute: typeof DistrictTingKauRoute
  DistrictTsuenWanRoute: typeof DistrictTsuenWanRoute
  EstateSlugRoute: typeof EstateSlugRoute
  PropertyListingNoRoute: typeof PropertyListingNoRoute
  ApiLiveAgentHandoffRoute: typeof ApiLiveAgentHandoffRoute
  ApiLiveAgentMessageRoute: typeof ApiLiveAgentMessageRoute
  ApiLiveAgentSessionRoute: typeof ApiLiveAgentSessionRoute
  ApiWoztellWebhookRoute: typeof ApiWoztellWebhookRoute
  ApiAdminAiRebuildKnowledgeRoute: typeof ApiAdminAiRebuildKnowledgeRoute
  ApiAdminJobsSendQueueRoute: typeof ApiAdminJobsSendQueueRoute
  ApiAdminMediaUploadRoute: typeof ApiAdminMediaUploadRoute
  ApiAdminWoztellSendRoute: typeof ApiAdminWoztellSendRoute
  ApiAdminCampaignsIdQueueRoute: typeof ApiAdminCampaignsIdQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castle-peak-road': {
      id: '/castle-peak-road'
      path: '/castle-peak-road'
      fullPath: '/castle-peak-road'
      preLoaderRoute: typeof CastlePeakRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castle-peak-road/': {
      id: '/castle-peak-road/'
      path: '/'
      fullPath: '/castle-peak-road/'
      preLoaderRoute: typeof CastlePeakRoadIndexRouteImport
      parentRoute: typeof CastlePeakRoadRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/property/$listingNo': {
      id: '/property/$listingNo'
      path: '/property/$listingNo'
      fullPath: '/property/$listingNo'
      preLoaderRoute: typeof PropertyListingNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate/$slug': {
      id: '/estate/$slug'
      path: '/estate/$slug'
      fullPath: '/estate/$slug'
      preLoaderRoute: typeof EstateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/tsuen-wan': {
      id: '/district/tsuen-wan'
      path: '/district/tsuen-wan'
      fullPath: '/district/tsuen-wan'
      preLoaderRoute: typeof DistrictTsuenWanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/ting-kau': {
      id: '/district/ting-kau'
      path: '/district/ting-kau'
      fullPath: '/district/ting-kau'
      preLoaderRoute: typeof DistrictTingKauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/sham-tseng': {
      id: '/district/sham-tseng'
      path: '/district/sham-tseng'
      fullPath: '/district/sham-tseng'
      preLoaderRoute: typeof DistrictShamTsengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/castle-peak-road/$segment': {
      id: '/castle-peak-road/$segment'
      path: '/$segment'
      fullPath: '/castle-peak-road/$segment'
      preLoaderRoute: typeof CastlePeakRoadSegmentRouteImport
      parentRoute: typeof CastlePeakRoadRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mls-sync': {
      id: '/api/mls-sync'
      path: '/api/mls-sync'
      fullPath: '/api/mls-sync'
      preLoaderRoute: typeof ApiMlsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segments': {
      id: '/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AdminSegmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blasts': {
      id: '/admin/blasts'
      path: '/blasts'
      fullPath: '/admin/blasts'
      preLoaderRoute: typeof AdminBlastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/property/new': {
      id: '/dashboard/property/new'
      path: '/property/new'
      fullPath: '/dashboard/property/new'
      preLoaderRoute: typeof DashboardPropertyNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/property/$id': {
      id: '/dashboard/property/$id'
      path: '/property/$id'
      fullPath: '/dashboard/property/$id'
      preLoaderRoute: typeof DashboardPropertyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/woztell/webhook': {
      id: '/api/woztell/webhook'
      path: '/api/woztell/webhook'
      fullPath: '/api/woztell/webhook'
      preLoaderRoute: typeof ApiWoztellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-agent/session': {
      id: '/api/live-agent/session'
      path: '/api/live-agent/session'
      fullPath: '/api/live-agent/session'
      preLoaderRoute: typeof ApiLiveAgentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-agent/message': {
      id: '/api/live-agent/message'
      path: '/api/live-agent/message'
      fullPath: '/api/live-agent/message'
      preLoaderRoute: typeof ApiLiveAgentMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-agent/handoff': {
      id: '/api/live-agent/handoff'
      path: '/api/live-agent/handoff'
      fullPath: '/api/live-agent/handoff'
      preLoaderRoute: typeof ApiLiveAgentHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings_/new': {
      id: '/admin/listings_/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings_/$id': {
      id: '/admin/listings_/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/woztell/send': {
      id: '/api/admin/woztell/send'
      path: '/api/admin/woztell/send'
      fullPath: '/api/admin/woztell/send'
      preLoaderRoute: typeof ApiAdminWoztellSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/upload': {
      id: '/api/admin/media/upload'
      path: '/api/admin/media/upload'
      fullPath: '/api/admin/media/upload'
      preLoaderRoute: typeof ApiAdminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/jobs/send-queue': {
      id: '/api/admin/jobs/send-queue'
      path: '/api/admin/jobs/send-queue'
      fullPath: '/api/admin/jobs/send-queue'
      preLoaderRoute: typeof ApiAdminJobsSendQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai/rebuild-knowledge': {
      id: '/api/admin/ai/rebuild-knowledge'
      path: '/api/admin/ai/rebuild-knowledge'
      fullPath: '/api/admin/ai/rebuild-knowledge'
      preLoaderRoute: typeof ApiAdminAiRebuildKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/campaigns/$id/queue': {
      id: '/api/admin/campaigns/$id/queue'
      path: '/api/admin/campaigns/$id/queue'
      fullPath: '/api/admin/campaigns/$id/queue'
      preLoaderRoute: typeof ApiAdminCampaignsIdQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlastsRoute: typeof AdminBlastsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlastsRoute: AdminBlastsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CastlePeakRoadRouteChildren {
  CastlePeakRoadSegmentRoute: typeof CastlePeakRoadSegmentRoute
  CastlePeakRoadIndexRoute: typeof CastlePeakRoadIndexRoute
}

const CastlePeakRoadRouteChildren: CastlePeakRoadRouteChildren = {
  CastlePeakRoadSegmentRoute: CastlePeakRoadSegmentRoute,
  CastlePeakRoadIndexRoute: CastlePeakRoadIndexRoute,
}

const CastlePeakRoadRouteWithChildren = CastlePeakRoadRoute._addFileChildren(
  CastlePeakRoadRouteChildren,
)

interface DashboardRouteChildren {
  DashboardInquiriesRoute: typeof DashboardInquiriesRoute
  DashboardPropertyIdRoute: typeof DashboardPropertyIdRoute
  DashboardPropertyNewRoute: typeof DashboardPropertyNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInquiriesRoute: DashboardInquiriesRoute,
  DashboardPropertyIdRoute: DashboardPropertyIdRoute,
  DashboardPropertyNewRoute: DashboardPropertyNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  BlogRoute: BlogRouteWithChildren,
  CastlePeakRoadRoute: CastlePeakRoadRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListingsRoute: ListingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AccountPathnameRoute: AccountPathnameRoute,
  ApiMlsSyncRoute: ApiMlsSyncRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  AuthLoginRoute: AuthLoginRoute,
  DistrictShamTsengRoute: DistrictShamTsengRoute,
  DistrictTingKauRoute: DistrictTingKauRoute,
  DistrictTsuenWanRoute: DistrictTsuenWanRoute,
  EstateSlugRoute: EstateSlugRoute,
  PropertyListingNoRoute: PropertyListingNoRoute,
  ApiLiveAgentHandoffRoute: ApiLiveAgentHandoffRoute,
  ApiLiveAgentMessageRoute: ApiLiveAgentMessageRoute,
  ApiLiveAgentSessionRoute: ApiLiveAgentSessionRoute,
  ApiWoztellWebhookRoute: ApiWoztellWebhookRoute,
  ApiAdminAiRebuildKnowledgeRoute: ApiAdminAiRebuildKnowledgeRoute,
  ApiAdminJobsSendQueueRoute: ApiAdminJobsSendQueueRoute,
  ApiAdminMediaUploadRoute: ApiAdminMediaUploadRoute,
  ApiAdminWoztellSendRoute: ApiAdminWoztellSendRoute,
  ApiAdminCampaignsIdQueueRoute: ApiAdminCampaignsIdQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
