/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyListingNoRouteImport } from './routes/property.$listingNo'
import { Route as EstateSlugRouteImport } from './routes/estate.$slug'
import { Route as DistrictTsuenWanRouteImport } from './routes/district.tsuen-wan'
import { Route as DistrictShamTsengRouteImport } from './routes/district.sham-tseng'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardPropertyNewRouteImport } from './routes/dashboard.property.new'
import { Route as DashboardPropertyIdRouteImport } from './routes/dashboard.property.$id'

const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyListingNoRoute = PropertyListingNoRouteImport.update({
  id: '/property/$listingNo',
  path: '/property/$listingNo',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateSlugRoute = EstateSlugRouteImport.update({
  id: '/estate/$slug',
  path: '/estate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictTsuenWanRoute = DistrictTsuenWanRouteImport.update({
  id: '/district/tsuen-wan',
  path: '/district/tsuen-wan',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictShamTsengRoute = DistrictShamTsengRouteImport.update({
  id: '/district/sham-tseng',
  path: '/district/sham-tseng',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertyNewRoute = DashboardPropertyNewRouteImport.update({
  id: '/property/new',
  path: '/property/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertyIdRoute = DashboardPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/district/sham-tseng': typeof DistrictShamTsengRoute
  '/district/tsuen-wan': typeof DistrictTsuenWanRoute
  '/estate/$slug': typeof EstateSlugRoute
  '/property/$listingNo': typeof PropertyListingNoRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdRoute
  '/dashboard/property/new': typeof DashboardPropertyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/auth/login'
    | '/district/sham-tseng'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/auth/login'
    | '/district/sham-tseng'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/listings'
    | '/auth/login'
    | '/district/sham-tseng'
    | '/district/tsuen-wan'
    | '/estate/$slug'
    | '/property/$listingNo'
    | '/dashboard/property/$id'
    | '/dashboard/property/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListingsRoute: typeof ListingsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DistrictShamTsengRoute: typeof DistrictShamTsengRoute
  DistrictTsuenWanRoute: typeof DistrictTsuenWanRoute
  EstateSlugRoute: typeof EstateSlugRoute
  PropertyListingNoRoute: typeof PropertyListingNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$listingNo': {
      id: '/property/$listingNo'
      path: '/property/$listingNo'
      fullPath: '/property/$listingNo'
      preLoaderRoute: typeof PropertyListingNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate/$slug': {
      id: '/estate/$slug'
      path: '/estate/$slug'
      fullPath: '/estate/$slug'
      preLoaderRoute: typeof EstateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/tsuen-wan': {
      id: '/district/tsuen-wan'
      path: '/district/tsuen-wan'
      fullPath: '/district/tsuen-wan'
      preLoaderRoute: typeof DistrictTsuenWanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/sham-tseng': {
      id: '/district/sham-tseng'
      path: '/district/sham-tseng'
      fullPath: '/district/sham-tseng'
      preLoaderRoute: typeof DistrictShamTsengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/property/new': {
      id: '/dashboard/property/new'
      path: '/property/new'
      fullPath: '/dashboard/property/new'
      preLoaderRoute: typeof DashboardPropertyNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/property/$id': {
      id: '/dashboard/property/$id'
      path: '/property/$id'
      fullPath: '/dashboard/property/$id'
      preLoaderRoute: typeof DashboardPropertyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPropertyIdRoute: typeof DashboardPropertyIdRoute
  DashboardPropertyNewRoute: typeof DashboardPropertyNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPropertyIdRoute: DashboardPropertyIdRoute,
  DashboardPropertyNewRoute: DashboardPropertyNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListingsRoute: ListingsRoute,
  AuthLoginRoute: AuthLoginRoute,
  DistrictShamTsengRoute: DistrictShamTsengRoute,
  DistrictTsuenWanRoute: DistrictTsuenWanRoute,
  EstateSlugRoute: EstateSlugRoute,
  PropertyListingNoRoute: PropertyListingNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
