import type { AuthLocalization } from "@neondatabase/auth-ui";

/** Labels supported by the installed AuthView. The provider still owns validation,
 * errors, redirects, callbacks and credential handling. */
export const staffAuthZhHK = {
  APP: "晉誠地產",
  SIGN_IN: "職員登入",
  SIGN_IN_ACTION: "登入",
  SIGN_IN_DESCRIPTION: "請輸入職員電郵及密碼。",
  SIGN_UP: "建立帳戶",
  SIGN_UP_ACTION: "建立帳戶",
  SIGN_UP_DESCRIPTION: "請輸入帳戶資料。",
  DONT_HAVE_AN_ACCOUNT: "還沒有帳戶？",
  ALREADY_HAVE_AN_ACCOUNT: "已有帳戶？",
  EMAIL_VERIFICATION: "驗證電郵",
  EMAIL_VERIFICATION_DESCRIPTION: "請按電郵中的連結完成驗證。",
  EMAIL_OTP: "電郵驗證碼",
  EMAIL_OTP_SEND_ACTION: "發送驗證碼",
  EMAIL_OTP_VERIFY_ACTION: "驗證",
  EMAIL: "電郵地址",
  EMAIL_DESCRIPTION: "請輸入登入用的電郵地址。",
  EMAIL_INSTRUCTIONS: "請輸入有效的電郵地址。",
  EMAIL_REQUIRED: "請輸入電郵地址",
  PASSWORD: "密碼",
  PASSWORD_PLACEHOLDER: "密碼",
  PASSWORD_REQUIRED: "請輸入密碼",
  REMEMBER_ME: "記住我",
  FORGOT_PASSWORD: "忘記密碼",
  FORGOT_PASSWORD_LINK: "忘記密碼？",
  FORGOT_PASSWORD_ACTION: "發送重設連結",
  FORGOT_PASSWORD_DESCRIPTION: "請輸入電郵地址以重設密碼。",
  FORGOT_PASSWORD_EMAIL: "如帳戶可使用，請查看電郵中的重設連結。",
  RESET_PASSWORD: "重設密碼",
  RESET_PASSWORD_ACTION: "儲存新密碼",
  RESET_PASSWORD_DESCRIPTION: "請輸入新密碼。",
  RESET_PASSWORD_SUCCESS: "密碼已重設",
  NEW_PASSWORD: "新密碼",
  NEW_PASSWORD_PLACEHOLDER: "新密碼",
  NEW_PASSWORD_REQUIRED: "請輸入新密碼",
  CONFIRM_PASSWORD: "確認密碼",
  CONFIRM_PASSWORD_PLACEHOLDER: "確認密碼",
  CONFIRM_PASSWORD_REQUIRED: "請再次輸入密碼",
  PASSWORDS_DO_NOT_MATCH: "兩次輸入的密碼不相同",
  GO_BACK: "返回",
  CANCEL: "取消",
  CONTINUE: "繼續",
  SIGN_OUT: "登出",
  REQUEST_FAILED: "暫時無法完成要求，請稍後再試。",
  SESSION_NOT_FRESH: "登入狀態已過期，請重新登入。",
} satisfies AuthLocalization;
